# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "sabre-sdk"
version = "0.8.2"
authors = ["Cargill, Incorporated"]
license = "Apache-2.0"
description = """\
    Sawtooth Sabre is a transaction family which implements on-chain smart \
    contracts executed in a WebAssembly virtual machine.
"""
documentation = "https://sawtooth.hyperledger.org/docs/1.2/sabre/"
edition = "2018"


[dependencies]
protobuf = "2.19"
sha2 = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
transact = "0.4"
cylinder = "0.2"

[build-dependencies]
protoc-rust = "2.14"
glob = "0.3"

[features]
default = []

stable = [
    # The stable feature extends default:
    "default",
    # The following features are stable:
]

experimental = [
    # The experimental feature extends stable:
    "stable",
    # The following features are experimental:
]
